# Generated by Django 2.0.7 on 2020-11-27 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=250)),
                ('file_attachment', models.FileField(upload_to='')),
                ('public_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('kategori', models.CharField(choices=[('AMI', 'AMI'), ('ABPT', 'ABPT'), ('Informasi Umum', 'Informasi Umum')], max_length=50)),
                ('public_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubFile01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=250)),
                ('file_attachment', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SubFile02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=250)),
                ('file_attachment', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SubFolder01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_folder', models.CharField(max_length=520)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='SubFolder02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_folder', models.CharField(max_length=250)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.SubFolder01')),
            ],
        ),
        migrations.AddField(
            model_name='subfile02',
            name='nama_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.SubFolder02'),
        ),
        migrations.AddField(
            model_name='subfile01',
            name='nama_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.SubFolder01'),
        ),
        migrations.AddField(
            model_name='folder',
            name='nama_prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upmsite.Prodi'),
        ),
        migrations.AddField(
            model_name='file',
            name='nama_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.Folder'),
        ),
    ]
