# Generated by Django 3.1.2 on 2020-12-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_folder', models.CharField(default='', max_length=256)),
                ('kategori', models.CharField(choices=[('AMI', 'AMI'), ('ABPT', 'ABPT'), ('Informasi Umum', 'Informasi Umum')], max_length=50)),
                ('public_status', models.BooleanField(default=True)),
                ('isAllowNewFolder', models.BooleanField(default=True)),
                ('isAllowNewFile', models.BooleanField(default=True)),
                ('nama_prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='SubFolder01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_folder', models.CharField(max_length=520)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.folder')),
            ],
        ),
        migrations.CreateModel(
            name='SubFolder02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_folder', models.CharField(max_length=250)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.subfolder01')),
            ],
        ),
        migrations.CreateModel(
            name='SubFile02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=250)),
                ('file_attachment', models.FileField(upload_to='')),
                ('nama_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.subfolder02')),
            ],
        ),
        migrations.CreateModel(
            name='SubFile01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=250)),
                ('file_attachment', models.FileField(upload_to='')),
                ('nama_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upmsite.subfolder01')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=250)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('public_status', models.BooleanField(default=True)),
                ('nama_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upmsite.folder')),
            ],
        ),
    ]
