# Generated by Django 3.1.2 on 2020-11-27 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upmsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='nama_prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upmsite.prodi'),
        ),
    ]
